// src/pages/CssConverter.tsx
import React from "react";

import WindNotify from "./WindNotify";

import { invoke } from "@tauri-apps/api/tauri";

class CssConverter extends React.Component {
  childRef: any = React.createRef();

  typeStyle: string = "";
  dataField: string = "";

  dataArr: Array<any> = [];

  state = {
    blockTable: false,
  };

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  };

  async componentDidMount() {
    await this.getDataFile();
  }

  getDataFile = async () => {
    await invoke("get_json")
    .then((json: any) => {
      if(json && json != '') this.dataArr = JSON.parse(json)["root"];
    })
    .catch((err: any) => console.error(err));
  }

  searchElemData = (item: string, style: string) => {
    let td = document.createElement('td');
    td.classList.add("styleTD");
    td.classList.add("whitespace-nowrap");
    let tempObj: {[key: string]: any} = { "color": "text", "background-color": "bg", "border-color": "border", "border-top-color": "border-t", "border-bottom-color": "border-b", "border-left-color": "border-l", "border-right-color": "border-r", "border-inline-start-color": "border-s", "border-inline-end-color": "border-e" };
    let regCSS = /([\w\-]*):\s*([\s\w\d\%\,\(\)\#\-]*);/;
    let propCSS = regCSS.exec(item);
    if(propCSS && propCSS![2].indexOf("rgb") >= 0) {
      for(let i = 0; i < 3; i++) {
        propCSS[2] = propCSS![2].replace(/\,\s*/, " ");
        item = item.replace(/\,\s*/, " ");
      }
    }
    let propTailwind = /([\w\/]*\-?\w?)-([\w\/\[\]\-]*)/.exec(item);
    let objItem;
    if(this.typeStyle == style){
      td.innerText = item;
    } else if(objItem = this.dataArr.find((obj: any) => obj[this.typeStyle] == item)){
      if(this.typeStyle == "css" && propCSS && Object.keys(tempObj).includes(propCSS![1])){
        td.innerText = (objItem[style]) ? `${tempObj[String(propCSS![1])]}-${objItem[style]}` : "";
      } else if(this.typeStyle != "css" && style == "css" && objItem[this.typeStyle] == propTailwind![2]){
        td.innerText = (objItem[style]) ? `${Object.keys(tempObj).find((elem: string) => tempObj[elem] == propTailwind![1])}: ${regCSS.exec(objItem[style])![2]};` : "";
      } else {
        td.innerText = (objItem[style]) ? objItem[style] : "";
      }
    } else if((propCSS && Object.keys(tempObj).includes(propCSS![1])) ||
      (propTailwind && Object.values(tempObj).includes(propTailwind![1]))){
      if(this.typeStyle == "css" && (objItem = this.dataArr.find((obj: any) => obj["css"] == `color: ${propCSS![2]};`))){
        if(objItem) td.innerText = (objItem[style]) ? `${tempObj[String(propCSS![1])]}-${objItem[style]}` : "";
        else td.innerText = "";
      } else if(this.typeStyle != "css" && (objItem = this.dataArr.find((obj: any) => obj[this.typeStyle] == propTailwind![2]))){
        if(objItem) td.innerText = (objItem[style]) ? Object.keys(tempObj).find((elem: string) => tempObj[elem] == propTailwind![1]) + ": " + regCSS.exec(objItem[style])![2] + ";" : "";
        else td.innerText = "";
      } else if(this.typeStyle == "css" && style == "tailwind" && propCSS){
        let key = this.dataArr.find((obj: any) => obj[style].indexOf(propCSS![1]))!["tailwind_custom"];
        if(Object.keys(tempObj).includes(propCSS![1])) key = tempObj[propCSS![1]];
        td.innerText = key + "-[" + propCSS![2] + "]";
      }
    } else if(this.typeStyle == "css" && style == "tailwind" && propCSS){
      let key = this.dataArr.find((obj: any) => obj[style].indexOf(propCSS![1]))!["tailwind_custom"];
      if(Object.keys(tempObj).includes(propCSS![1])) key = tempObj[propCSS![1]];
      td.innerText = key + "-[" + propCSS![2] + "]";
    }
    return td;
  }

  convertData = async () => {
    if(this.dataField != '' && this.typeStyle != ''){
      this.setState({
        blockTable: true,
      });

      let listField = (this.typeStyle != "css") ? this.dataField.match(/[\w\d\/\[\]\-]*[^\s*\n*]/gm) : this.dataField.match(/[\w\-]*:\s*[\s\w\d\%\,\(\)\#\-]*;/gm);

      const table = document.createElement('table');

      if(listField){
        let tr = document.createElement('tr');
        listField.unshift("Data Field");
        listField.forEach((item: string) => {
          let th = document.createElement('th');
          th.innerText = item;
          th.classList.add("styleTD");
          th.classList.add("whitespace-nowrap");
          tr.appendChild(th);
        });
        listField.shift();
        table.appendChild(tr);
      }

      let objStyles = {"css": "CSS", "bootstrap": "Bootstrap 5", "tailwind": "Tailwind CSS"};

      Object.entries(objStyles).forEach(([key, value]) => {
        let tr = document.createElement('tr');
        let th = document.createElement('th');
        th.innerText = value;
        th.classList.add("styleTD");
        th.classList.add("whitespace-nowrap");
        tr.appendChild(th);
        if(listField){
          listField.forEach((item: string) => {
            tr.appendChild(this.searchElemData(item, key));
          });
        }
        table.appendChild(tr);
      });

      setTimeout(() => {
        const blockTable = document.querySelector('#blockTable') as HTMLDivElement | null;
        if(blockTable != null) {
          blockTable.innerHTML = "";
          blockTable.appendChild(table);
        }
      }, 500);
    } else if (this.typeStyle == '') {
      this.alertNotify("bg-red-700", "You have not selected the type of source styles!");
    } else if (this.dataField == '') {
      this.alertNotify("bg-red-700", "The field is empty! Insert the data!");
    }
  };

  render (){
    return (
      <>
        <div className="flex flex-col gap-y-3">
          <span className="text-2xl font-bold border-b-2 styleBorderSolid">CSS Converter to classes CSS Frameworks</span>

          <span className="styleLabel">Choose a style type</span>
          <div className="flex flex-row gap-x-5">
            <div className="flex flex-row gap-x-2 justify-center content-center">
              <label className="styleLabel !mt-0">
                <input className="styleRadio mr-2" type="radio" name="typeStyle" onChange={() => {this.typeStyle = "css"}} />
                <span>CSS</span>
              </label>
            </div>

            <div className="flex flex-row gap-x-2 justify-center content-center">
              <label className="styleLabel !mt-0">
                <input className="styleRadio mr-2" type="radio" name="typeStyle" onChange={() => {this.typeStyle = "bootstrap"}} />
                <span>Bootstrap 5</span>
              </label>
            </div>

            <div className="flex flex-row gap-x-2 justify-center content-center">
              <label className="styleLabel !mt-0">
                <input className="styleRadio mr-2" type="radio" name="typeStyle" onChange={() => {this.typeStyle = "tailwind"}} />
                <span>Tailwind CSS</span>
              </label>
            </div>
          </div>

          <div className="flex flex-col gap-y-3">
            <label className="styleLabel">Enter the style according to the selected type (you can enter several classes or properties separated by a space)</label>
            <textarea className="styleTextarea" onChange={(event: any) => {this.dataField = event.target.value}} rows={2}></textarea>
            <button className="styleBut w-max" onClick={() => {this.convertData()}}>Convert data</button>
          </div>

          {this.state.blockTable && <div className="overflow-x-auto" id="blockTable"></div>}

          <WindNotify ref={this.childRef} />
        </div>
      </>
    );
  };
};

export default CssConverter;

// src/app/views/css-converter/css-converter.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { invoke } from '@tauri-apps/api/tauri';
import { Subject } from 'rxjs';

/* components */
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

interface TableData {
  thead: Array<any>;
  tbody: Array<any>;
}

@Component({
  selector: 'app-css-converter',
  standalone: true,
  imports: [CommonModule, WindowNotifyComponent],
  templateUrl: './css-converter.component.html'
})
export class CssConverterComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();

  typeStyle: string = "";
  dataField: string = "";
  dataArr: Array<any> = [];

  dataTable: TableData = { thead: [], tbody: [] };
  blockTable: boolean = false;

  ngOnInit(): void {
    this.getDataFile();
  }
  
  async getDataFile() {
    await invoke("get_css_library")
    .then((json: any) => {
      if (json && json != '') {
        this.dataArr = JSON.parse(json)["root"];
      }
    })
    .catch((err: any) => console.error(err));
  }

  setTypeStyle(type: string) {
    this.typeStyle = type;
  }

  setData(event: any) {
    this.dataField = event.target.value;
  }

  searchElemData(item: string, style: string) {
    let textElem = '';
    try {
      let tempObj: {[key: string]: any} = { "color": "text", "background-color": "bg", "border-color": "border", "border-top-color": "border-t", "border-bottom-color": "border-b", "border-left-color": "border-l", "border-right-color": "border-r", "border-inline-start-color": "border-s", "border-inline-end-color": "border-e" };
      let regCSS = /([\w\-]*):\s*([\s\w\d\%\,\(\)\#\-]*);/;
      let propCSS = regCSS.exec(item);
      if (propCSS && propCSS![2].indexOf("rgb") >= 0) {
        for(let i = 0; i < 3; i++) {
          propCSS[2] = propCSS![2].replace(/\,\s*/, " ");
          item = item.replace(/\,\s*/, " ");
        }
      }
      let propTailwind = /^(\w+)(?:-([\w\/\[\]]+))?(?:-([\w\/\[\]]+))?(?:-([\w\/\[\]]+))?$/.exec(item);
      if (propTailwind && propTailwind![3] && propTailwind![4]) {
        if (Object.values(tempObj).includes(propTailwind![1] + '-' + propTailwind![2])) {
          propTailwind![1] = propTailwind![1] + '-' + propTailwind![2];
          propTailwind![2] = propTailwind![3] + '-' + propTailwind![4];
          propTailwind![3] = '';
          propTailwind![4] = '';
        } else {
          propTailwind![2] = propTailwind![2] + '-' + propTailwind![3] + '-' + propTailwind![4];
          propTailwind![3] = '';
          propTailwind![4] = '';
        }
      } else if (propTailwind && propTailwind![3]) {
        if (Object.values(tempObj).includes(propTailwind![1] + '-' + propTailwind![2])) {
          propTailwind![1] = propTailwind![1] + '-' + propTailwind![2];
          propTailwind![2] = propTailwind![3];
          propTailwind![3] = '';
        } else {
          propTailwind![2] = propTailwind![2] + '-' + propTailwind![3];
          propTailwind![3] = '';
        }
      }
      let objItem;
      if (this.typeStyle == style) {
        textElem = item;
      } else if (objItem = this.dataArr.find((obj: any) => obj[this.typeStyle] == item)) {
        if (propCSS && Object.keys(tempObj).includes(propCSS![1])) {
          textElem = (objItem[style]) ? `${tempObj[String(propCSS![1])]}-${objItem[style]}` : "";
        } else {
          textElem = (objItem[style]) ? objItem[style] : "";
        }
      } else if ((propCSS && Object.keys(tempObj).includes(propCSS![1])) ||
                (propTailwind && Object.values(tempObj).includes(propTailwind![1]))) {
        if (this.typeStyle == "css" && (objItem = this.dataArr.find((obj: any) => obj["css"] == `color: ${propCSS![2]};`))) {
          if (objItem) {
            textElem = (objItem[style]) ? `${tempObj[String(propCSS![1])]}-${objItem[style]}` : "";
          } else {
            textElem = "";
          }
        } else if (this.typeStyle != "css" && style == "css" && (objItem = this.dataArr.find((obj: any) => obj[this.typeStyle] == propTailwind![2]))) {
          if (objItem) {
            textElem = (objItem[style]) ? `${Object.keys(tempObj).find((elem: string) => tempObj[elem] == propTailwind![1])}: ${regCSS.exec(objItem["css"])![2]};` : "";
          } else {
            textElem = "";
          }
        } else if (this.typeStyle != "css" && style != "css" && (objItem = this.dataArr.find((obj: any) => obj[this.typeStyle] == propTailwind![2]))) {
          if (objItem) {
            textElem = (objItem[style]) ? `${propTailwind![1]}-${objItem[style]}` : "";
          } else {
            textElem = "";
          }
        } else if (this.typeStyle == "css" && style == "tailwind" && propCSS) {
          let key = this.dataArr.find((obj: any) => obj[style].indexOf(propCSS![1]))!["tailwind_custom"];
          if (Object.keys(tempObj).includes(propCSS![1])) {
            key = tempObj[propCSS![1]];
          }
          textElem = key + "-[" + propCSS![2] + "]";
        }
      } else if (this.typeStyle == "css" && style == "tailwind" && propCSS) {
        let key = this.dataArr.find((obj: any) => obj[style].indexOf(propCSS![1]))!["tailwind_custom"];
        if (Object.keys(tempObj).includes(propCSS![1])) {
          key = tempObj[propCSS![1]];
        }
        textElem = key + "-[" + propCSS![2] + "]";
      }
    } catch (err: any) {
      this.dataNotify.next({ status: "error", text: err });
      console.error(err);
    }
    return textElem;
  }

  async convertData() {
    if (this.dataArr.length > 0 && this.dataField != '' && this.typeStyle != '') {
      this.blockTable = true;

      let listField = (this.typeStyle != "css") ? this.dataField.match(/[\w\d\/\[\]\-]*[^\s*\n*]/gm) : this.dataField.match(/[\w\-]*:\s*[\s\w\d\%\,\(\)\#\-]*;/gm);

      let tempHead: Array<any> = [];
      if (listField) {
        listField.unshift("Data Field");
        listField.forEach((item: string) => {
          tempHead.push(item);
        });
        listField.shift();
      }
      
      let objStyles = {"css": "CSS", "bootstrap": "Bootstrap 5", "tailwind": "Tailwind CSS"};
      
      let tempBody: Array<any> = [];
      Object.entries(objStyles).forEach(([key, value]) => {
        let tempRow: Array<any> = [];
        tempRow.push({"elem": "th", "text": value});
        if (listField) {
          listField.forEach((item: string) => {
            tempRow.push({"elem": "td", "text": this.searchElemData(item, key)});
          });
        }
        tempBody.push(tempRow);
      });
      
      setTimeout(() => {
        this.dataTable = {
          "thead": tempHead,
          "tbody": tempBody,
        }
      }, 500);
    } else if (this.dataArr.length == 0) {
      this.dataNotify.next({ status: "error", text: "You don't have a style library! Download it from the git repository from this program!" });
    } else if (this.typeStyle == '') {
      this.dataNotify.next({ status: "error", text: "You have not selected the type of source styles!" });
    } else if (this.dataField == '') {
      this.dataNotify.next({ status: "error", text: "The field is empty! Insert the data!" });
    }
  }
}

<div class="flex flex-col gap-y-5 w-full">
  <label class="styleLabel">Choose a style type</label>
  <div class="flex flex-row gap-x-5">
    <div class="flex flex-row gap-x-2 justify-center content-center">
      <label class="styleLabel !mt-0">
        <input class="styleRadio mr-2" type="radio" name="typeStyle" (change)="setTypeStyle('css')" />
        <span>CSS</span>
      </label>
    </div>

    <div class="flex flex-row gap-x-2 justify-center content-center">
      <label class="styleLabel !mt-0">
        <input class="styleRadio mr-2" type="radio" name="typeStyle" (change)="setTypeStyle('bootstrap')" />
        <span>Bootstrap 5</span>
      </label>
    </div>

    <div class="flex flex-row gap-x-2 justify-center content-center">
      <label class="styleLabel !mt-0">
        <input class="styleRadio mr-2" type="radio" name="typeStyle" (change)="setTypeStyle('tailwind')" />
        <span>Tailwind CSS</span>
      </label>
    </div>
  </div>

  <div class="flex flex-col gap-y-3">
    <label class="styleLabel">Enter the style according to the selected type (you can enter several classes or properties separated by a space)</label>
    <textarea class="styleTextarea" (change)="setData($event)" rows="2"></textarea>
    <button class="styleBut w-max" (click)="convertData()">Convert data</button>
  </div>

  @if (blockTable) {
    <div class="overflow-x-auto" id="blockTable">
      <table class="border styleBorderSolid">
        <thead>
          <tr>
            @for (th of dataTable.thead; track th) {
              <th class="styleTD whitespace-nowrap">{{th}}</th>
            }
          </tr>
        </thead>
        <tbody>
          @for (row of dataTable.tbody; track row) {
            <tr>
              @for (cell of row; track cell) {
                @if (cell.elem == "th") {
                  <th class="styleTD whitespace-nowrap">{{cell.text}}</th>
                } @else {
                  <td class="styleTD whitespace-nowrap">{{cell.text}}</td>
                }
              }
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>
