// src/pages/JsonToXml.tsx
import React from "react";

import WindNotify from "./WindNotify";

import { invoke } from "@tauri-apps/api/tauri";

class JsonToXml extends React.Component {
  childRef: any = React.createRef();

  file: any = null;
  dataField: string = "";
  dataXml: string = "";

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  };

  parseData(object: {[key: string]: any}, stroke: string = ''){
    var tempElement = '';
    Object.entries(object).forEach(([key, value]) => {
      if(Array.isArray(value)) {
        tempElement += `${this.parseData(value, key)}`;
      } else if(typeof value != 'string'){
        key = (isNaN(+key)) ? key : stroke;
        key = key.replace(" ", "");
        tempElement += `<${key}>${this.parseData(value, key)}</${key}>`;
      } else {
        key = key.replace(" ", "");
        tempElement += `<${key}>${value}</${key}>`;
      }
    });
    return tempElement;
  };

  convertDataFun = (dataJSON: {[key: string]: any}) => {
    this.dataXml = this.parseData(dataJSON);
    if (this.dataXml != '') {
      this.alertNotify("bg-green-700", "The data has been successfully converted!");
    } else {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  };

  parseDataFileFun = async () => {
    if(this.file != null){
      const fileUrl = URL.createObjectURL(this.file);
      const response = await fetch(fileUrl);
      const text = await response.text();
      if(text != null && text != ''){
        const dataJson = JSON.parse(text);
        this.convertDataFun(dataJson);
      }
    } else {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    }
  };

  parseDataFieldFun = () => {
    if(this.dataField != ''){
      const dataJson = JSON.parse(this.dataField);
      this.convertDataFun(dataJson);
    } else {
      this.alertNotify("bg-red-700", "The field is empty! Insert the data!");
    }
  };

  saveDataFileFun = async () => {
    if(this.file != null || this.dataXml != ''){
      await invoke("json_to_xml", {"name": (this.file) ? /^(.+)\..+$/.exec(this.file["name"])![1] : 'json_to_xml', "data": this.dataXml})
      .then((data: any) => {
        this.alertNotify("bg-green-700", `The data has been successfully saved to a file "${data}"!`);
      })
      .catch((err: any) => console.error(err));
    } else if(this.file == null){
      this.alertNotify("bg-red-700", "You have not selected a file!");
    } else if (this.dataXml == ''){
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  };

  render(){
    return (
      <>
        <div className="flex flex-col gap-y-3">
          <span className="text-2xl font-bold border-b-2 styleBorderSolid">Converter JSON to XML</span>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Select the JSON file with the data</span>
            </summary>
            
            <div className="flex flex-col gap-y-3">
              <input className="styleFileInput" type="file" onChange={(event: any) => {this.file = event.target.files[0]}} accept=".json" />
              <button className="styleBut w-max" onClick={() => {this.parseDataFileFun()}}>Convert a data</button>
            </div>
          </details>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Insert JSON data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <textarea className="styleTextarea" name="field" onChange={(event: any) => {this.dataField = event.target.value}} rows={7}></textarea>
              <button className="styleBut w-max" onClick={() => {this.parseDataFieldFun()}}>Convert a data</button>
            </div>
          </details>

          <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.saveDataFileFun()}}>Save a data</button>
          </div>
        </div>

        <WindNotify ref={this.childRef} />
      </>
    );
  };
};

export default JsonToXml;

// src/app/views/json-to-xml/json-to-xml.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { invoke } from '@tauri-apps/api/tauri';
import { Subject } from 'rxjs';

/* components */
import { FileInputComponent } from '@views/shared/fields/file-input/file-input.component';
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

@Component({
  selector: 'app-json-to-xml',
  standalone: true,
  imports: [CommonModule, FileInputComponent, WindowNotifyComponent],
  templateUrl: './json-to-xml.component.html'
})
export class JsonToXmlComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();
  
  typeFile: string = 'json';
  fileName: string = '';
  dataJson: {[key: string]: any} = {};
  dataXml: string = '';
  pathNewFile: string = '';

  ngOnInit(): void {}

  setDataFile(dataFile: any) {
    this.dataJson = JSON.parse(dataFile);
  }

  setFileName(event: any) {
    this.fileName = event;
  }

  setData(event: any) {
    try {
      this.dataJson = JSON.parse(event.target.value);
    } catch (err: any) {
      console.error(err);
      this.dataNotify.next({ status: 'error', text: err.toString() });
    }
  }

  parseData(obj: {[key: string]: any}, stroke: string = '') {
    let tempElement = '';
    Object.entries(obj).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        tempElement += `${this.parseData(value, key)}`;
      } else if (typeof value == 'object') {
        key = (isNaN(+key)) ? key : stroke;
        key = key.replace(/[\" \"]/gi,"");
        tempElement += `<${key}>${this.parseData(value, key)}</${key}>`;
      } else {
        key = key.replace(/[\" \"]/gi,"");
        tempElement += `<${key}>${value}</${key}>`;
      }
    });
    return tempElement;
  }

  convertData() {
    if (Object.keys(this.dataJson).length > 0) {
      this.dataXml = `<xml>${this.parseData(this.dataJson)}</xml>`;
      if (this.dataXml != '') {
        this.dataNotify.next({ status: 'success', text: "The data has been successfully converted!" });
      } else {
        this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
      }
    } else {
      this.dataNotify.next({ status: 'error', text: "There is no data for conversion!" });
    }
  }

  async saveData() {
    if (this.dataXml != '') {
      const nameNewFile = (this.fileName != '') ? /^(.+)\..+$/.exec(this.fileName)![1] : 'json_to_xml';
      await invoke("write_data_to_file", {"name": nameNewFile, "data": this.dataXml, "ext": "xml"})
      .then((data: any) => {
        this.pathNewFile = data;
        this.dataNotify.next({ status: 'success', text: `The data has been successfully saved to a file "${data}"!` });
      })
      .catch((err: any) => console.error(err));
    } else if (this.dataXml == '') {
      this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
    }
  }

  async openFile() {
    if (this.pathNewFile != '') {
      await invoke("open_file_in_app", {"path": this.pathNewFile})
      .then(() => {
        this.dataNotify.next({ status: 'warning', text: "Wait a bit until the program starts to read this file format!" });
      })
      .catch((err: any) => console.error(err));
    } else {
      this.dataNotify.next({ status: 'error', text: "You didn't save the file to open it!" });
    }
  }
}

<div class="flex flex-col gap-y-5 w-full">
  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Select the JSON file with the data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <app-file-input [typeFile]="typeFile" (dataFile)="setDataFile($event)" (reciveFileName)="setFileName($event)"></app-file-input>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Insert JSON data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <textarea class="styleTextarea" (change)="setData($event)" rows="7"></textarea>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  @if (dataXml != '') {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="saveData()">Save a data</button>
    </div>
  }

  @if (pathNewFile != '') {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="openFile()">Open the last saved file</button>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>
