// src/pages/JsonToXls.tsx
import React from "react";
import { invoke } from "@tauri-apps/api/tauri";
import { Link } from "react-router-dom";
import { ChevronBackCircleOutline } from "react-ionicons";

import WindNotify from "./WindNotify";

class JsonToXls extends React.Component<{numWind: number, onChangeData: any}> {
  constructor(props: any) {
    super(props);
  }

  childRef: any = React.createRef();

  file: any = null;
  dataField: string = "";
  dataXls: Array<Array<string>> = [];
  
  state = {
    pathNewFile: ""
  }

  changeNumWind(numWind: number) {
    this.props.onChangeData(Number(numWind));
  }

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  }

  parseArr(arr: Array<any>, startPos: number = 0) {
    let table: Array<Array<string>> = [];
    let tempHead: Array<string> = [];
    tempHead.push(...Array(startPos).fill(""));
    arr.forEach((elem: any) => {
      Object.keys(elem).forEach((key: string) => {
        if (!tempHead.includes(key)) {
          if (Array.isArray(elem[key])) {
            tempHead.push(...[key, ...Array(elem[key].length).fill('')]);
          } else if (typeof elem[key] === "object" && !Array.isArray(elem[key])) {
            tempHead.push(...[key, '']);
          } else {
            tempHead.push(key);
          }
        }
      });
    });
    table.push(tempHead);

    arr.forEach((elem: any) => {
      let tempRow: Array<string> = [];
      tempRow.push(...Array(startPos).fill(''));
      tempHead.forEach((key: string) => {
        if (elem[key] !== undefined && elem[key] !== null) {
          tempRow.push(elem[key].toString());
        }
      });
      table.push(tempRow);
      // tempHead.forEach((key: string, index: number) => {
      //   const value = elem[key];
      //   if (value != undefined && value != null && Array.isArray(value) && typeof(value[0]) == "object") {
      //     // tempRow.push(this.parseArr(value));
      //     this.parseObj(elem, startPos + index).forEach((row: Array<string>, iRow: number) => {
      //       console.log('58 line: ', row)
      //       if (iRow == 0) {
      //         tempRow.push(...row.slice(startPos + index));
      //         table.push(tempRow);
      //       } else {
      //         table.push(row);
      //       }
      //     });
      //   } else if (value != undefined && value != null && !Array.isArray(value) && typeof(value) == "object") {
      //     console.log(startPos, index)
      //     this.parseObj(value, /* startPos + */ index).forEach((row: Array<string>, iRow: number) => {
      //       console.log('68 line: ', row)
      //       if (iRow == 0) {
      //         tempRow.push(...row.slice(/* startPos + */ index));
      //         table.push(tempRow);
      //       } else {
      //         table.push(row);
      //       }
      //     });
      //   } else if (value != undefined && value != null) {
      //     tempRow.push(value.toString());
      //   }
      // });
      // if (Object.values(elem).findIndex((value: any) => typeof value === "object" || Array.isArray(value)) == -1) {
      //   table.push(tempRow);
      // }
    });
    return table;
  }

  parseObj(obj: {[key: string]: any}, startPos: number = 0) {
    let table: Array<Array<string>> = [];
    let tempHead: Array<string> = [];
    tempHead.push(...[...Array(startPos).fill(''), 'Key', 'Value']);
    table.push(tempHead);
    Object.entries(obj).forEach(([key, value]) => {
      let tempRow: Array<string> = [];
      tempRow.push(...[...Array(startPos).fill(''), key]);
      if (value == null) {
        tempRow.push("null");
        table.push(tempRow);
      } else if (Array.isArray(value) && typeof(value[0]) == "object") {
        this.parseArr(value, startPos + 1).forEach((row: Array<string>, iRow: number) => {
          if (iRow == 0) {
            tempRow.push(...row.slice(startPos + 1));
            table.push(tempRow);
          } else {
            table.push(row);
          }
        });
      } else if (!Array.isArray(value) && typeof(value) == "object") {
        this.parseObj(value, startPos + 1).forEach((row: Array<string>, iRow: number) => {
          if (iRow == 0) {
            tempRow.push(...row.slice(startPos + 1));
            table.push(tempRow);
          } else {
            table.push(row);
          }
        });
      } else {
        tempRow.push(value.toString());
        table.push(tempRow);
      }
    });
    return table;
  }

  convertDataFun(dataJson: {[key: string]: any}) {
    this.dataXls = this.parseObj(dataJson);

    if (Array.isArray(this.dataXls)) {
      this.alertNotify("bg-green-700", "The data has been successfully converted!");
    } else {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  }

  async parseDataFileFun() {
    if (this.file != null) {
      const fileUrl = URL.createObjectURL(this.file);
      const response = await fetch(fileUrl);
      const text = await response.text();
      if (text != null && text != '') {
        const dataJson = JSON.parse(text);
        this.convertDataFun(dataJson);
      } else {
        this.alertNotify("bg-red-700", "The file is empty!");
      }
    } else {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    }
  }

  parseDataFieldFun() {
    if (this.dataField != '') {
      const dataJson = JSON.parse(this.dataField);
      this.convertDataFun(dataJson);
    } else {
      this.alertNotify("bg-red-700", "The field is empty! Insert the data!");
    }
  }

  async saveDataFileFun() {
    if (this.file != null || this.dataXls.length > 0) {
      const nameNewFile = (this.file) ? /^(.+)\..+$/.exec(this.file["name"])![1] : 'json_to_xls';
      await invoke("json_to_xls", {"name": nameNewFile, "data": this.dataXls})
      .then((data: any) => {
        this.setState({
          pathNewFile: data
        });
        this.alertNotify("bg-green-700", `The data has been successfully saved to a file "${data}"!`);
      })
      .catch((err: any) => console.error(err));
    } else if (this.file == null) {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    } else if (this.dataXls.length == 0) {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  }

  async openFileFun() {
    if (this.state.pathNewFile != '') {
      await invoke("open_file", {"path": this.state.pathNewFile})
      .then(() => {
        this.alertNotify("bg-green-700", "Wait a bit until the program starts to read this file format!");
      })
      .catch((err: any) => console.error(err));
    } else {
      this.alertNotify("bg-red-700", "You didn't save the file to open it!");
    }
  }

  render() {
    return (
      <>
        <div className={`flex flex-col gap-y-5 ${(this.props.numWind > 2) ? 'w-full lg:w-1/3' : (this.props.numWind > 1) ? 'w-full lg:w-1/2' : 'w-full'}`}>
          <div className="flex flex-row justify-between items-center border-b-2 styleBorderSolid pb-2">
            <div className="flex flex-row gap-x-2 text-2xl font-bold">
              <Link to="/"><ChevronBackCircleOutline cssClasses="styleIonIcon" /></Link>
              <span>Converter JSON to XLS</span>
            </div>
            <select className="styleSelect !w-min" onChange={(event: any) => {this.changeNumWind(event.target.value)}} value={this.props.numWind}>
              <option value={1}>1 window</option>
              <option value={2}>2 windows</option>
              <option value={3}>3 windows</option>
            </select>
          </div>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Select the JSON file with the data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <input className="styleFileInput" type="file" onChange={(event: any) => {this.file = event.target.files[0]}} accept=".json" />
              <button className="styleBut w-max" onClick={() => {this.parseDataFileFun()}}>Convert a data</button>
            </div>
          </details>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Insert JSON data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <textarea className="styleTextarea" name="field" onChange={(event: any) => {this.dataField = event.target.value}} rows={7}></textarea>
              <button className="styleBut w-max" onClick={() => {this.parseDataFieldFun()}}>Convert a data</button>
            </div>
          </details>
          
          <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.saveDataFileFun()}}>Save a data</button>
          </div>

          {this.state.pathNewFile != '' && <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.openFileFun()}}>Open the last saved file</button>
          </div>}
        </div>

        <WindNotify ref={this.childRef} />
      </>
    );
  };
};

export default JsonToXls;

// src/app/views/json-to-xls/json-to-xls.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { invoke } from '@tauri-apps/api/tauri';
import { Subject } from 'rxjs';

/* components */
import { FileInputComponent } from '@views/shared/fields/file-input/file-input.component';
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

@Component({
  selector: 'app-json-to-xls',
  standalone: true,
  imports: [CommonModule, FileInputComponent, WindowNotifyComponent],
  templateUrl: './json-to-xls.component.html'
})
export class JsonToXlsComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();
  
  typeFile: string = 'json';
  fileName: string = '';
  dataJson: {[key: string]: any} = {};
  dataXls: Array<any> = [];
  pathNewFile: string = '';

  ngOnInit(): void {}

  setDataFile(dataFile: any) {
    this.dataJson = JSON.parse(dataFile);
  }

  setFileName(event: any) {
    this.fileName = event;
  }

  setData(event: any) {
    try {
      this.dataJson = JSON.parse(event.target.value);
    } catch (err: any) {
      console.error(err);
      this.dataNotify.next({ status: 'error', text: err.toString() });
    }
  }

  parseArr(arr: Array<any>, startPos: number = 0) {
    let table: Array<Array<string>> = [];
    let tempHead: Array<string> = [];
    tempHead.push(...Array(startPos).fill(""));
    arr.forEach((elem: any) => {
      Object.keys(elem).forEach((key: string) => {
        if (!tempHead.includes(key)) {
          if (Array.isArray(elem[key])) {
            tempHead.push(...[key, ...Array(elem[key].length).fill('')]);
          } else if (typeof elem[key] === "object" && !Array.isArray(elem[key])) {
            tempHead.push(...[key, '']);
          } else {
            tempHead.push(key);
          }
        }
      });
    });
    table.push(tempHead);

    arr.forEach((elem: any) => {
      let tempRow: Array<string> = [];
      tempRow.push(...Array(startPos).fill(''));
      tempHead.forEach((key: string) => {
        if (elem[key] !== undefined && elem[key] !== null) {
          tempRow.push(elem[key].toString());
        }
      });
      table.push(tempRow);
      // tempHead.forEach((key: string, index: number) => {
      //   const value = elem[key];
      //   if (value != undefined && value != null && Array.isArray(value) && typeof(value[0]) == "object") {
      //     // tempRow.push(this.parseArr(value));
      //     this.parseObj(elem, startPos + index).forEach((row: Array<string>, iRow: number) => {
      //       console.log('58 line: ', row)
      //       if (iRow == 0) {
      //         tempRow.push(...row.slice(startPos + index));
      //         table.push(tempRow);
      //       } else {
      //         table.push(row);
      //       }
      //     });
      //   } else if (value != undefined && value != null && !Array.isArray(value) && typeof(value) == "object") {
      //     console.log(startPos, index)
      //     this.parseObj(value, /* startPos + */ index).forEach((row: Array<string>, iRow: number) => {
      //       console.log('68 line: ', row)
      //       if (iRow == 0) {
      //         tempRow.push(...row.slice(/* startPos + */ index));
      //         table.push(tempRow);
      //       } else {
      //         table.push(row);
      //       }
      //     });
      //   } else if (value != undefined && value != null) {
      //     tempRow.push(value.toString());
      //   }
      // });
      // if (Object.values(elem).findIndex((value: any) => typeof value === "object" || Array.isArray(value)) == -1) {
      //   table.push(tempRow);
      // }
    });
    return table;
  }

  parseObj(obj: {[key: string]: any}, startPos: number = 0) {
    let table: Array<Array<string>> = [];
    let tempHead: Array<string> = [];
    tempHead.push(...[...Array(startPos).fill(''), 'Key', 'Value']);
    table.push(tempHead);
    Object.entries(obj).forEach(([key, value]) => {
      let tempRow: Array<string> = [];
      tempRow.push(...[...Array(startPos).fill(''), key]);
      if (value == null) {
        tempRow.push("null");
        table.push(tempRow);
      } else if (Array.isArray(value) && typeof(value[0]) == "object") {
        this.parseArr(value, startPos + 1).forEach((row: Array<string>, iRow: number) => {
          if (iRow == 0) {
            tempRow.push(...row.slice(startPos + 1));
            table.push(tempRow);
          } else {
            table.push(row);
          }
        });
      } else if (!Array.isArray(value) && typeof(value) == "object") {
        this.parseObj(value, startPos + 1).forEach((row: Array<string>, iRow: number) => {
          if (iRow == 0) {
            tempRow.push(...row.slice(startPos + 1));
            table.push(tempRow);
          } else {
            table.push(row);
          }
        });
      } else {
        tempRow.push(value.toString());
        table.push(tempRow);
      }
    });
    return table;
  }

  convertData() {
    if (Object.keys(this.dataJson).length > 0) {
      // this.dataXls = this.parseObj(this.dataJson);
  
      if (this.dataXls.length > 0) {
        this.dataNotify.next({ status: 'success', text: "The data has been successfully converted!" });
      } else {
        this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
      }
    } else {
      this.dataNotify.next({ status: 'error', text: "There is no data for conversion!" });
    }
  }

  async saveData() {
    if (this.dataXls.length > 0) {
      const nameNewFile = (this.fileName != '') ? /^(.+)\..+$/.exec(this.fileName)![1] : 'json_to_xls';
      await invoke("write_xls_data_to_file", {"name": nameNewFile, "data": this.dataXls})
      .then((data: any) => {
        this.pathNewFile = data;
        this.dataNotify.next({ status: 'success', text: `The data has been successfully saved to a file "${data}"!` });
      })
      .catch((err: any) => console.error(err));
    } else if (this.dataXls.length == 0) {
      this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
    }
  }

  async openFile() {
    if (this.pathNewFile != '') {
      await invoke("open_file_in_app", {"path": this.pathNewFile})
      .then(() => {
        this.dataNotify.next({ status: 'warning', text: "Wait a bit until the program starts to read this file format!" });
      })
      .catch((err: any) => console.error(err));
    } else {
      this.dataNotify.next({ status: 'error', text: "You didn't save the file to open it!" });
    }
  }
}

<div class="flex flex-col gap-y-5 w-full">
  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Select the JSON file with the data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <app-file-input [typeFile]="typeFile" (dataFile)="setDataFile($event)" (reciveFileName)="setFileName($event)"></app-file-input>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Insert JSON data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <textarea class="styleTextarea" (change)="setData($event)" rows="7"></textarea>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  @if (dataXls.length > 0) {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="saveData()">Save a data</button>
    </div>
  }

  @if (pathNewFile != '') {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="openFile()">Open the last saved file</button>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>
