// src/app/views/about/about.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { Subject } from 'rxjs';

/* env */
import { environvent } from '@env/environment';

/* services */
import { AboutService } from '@services/about.service';

/* components */
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

@Component({
  selector: 'app-about',
  standalone: true,
  providers: [AboutService],
  imports: [CommonModule, HttpClientModule, WindowNotifyComponent],
  templateUrl: './about.component.html'
})
export class AboutComponent {
  title: string = '';
  
  constructor(
    private aboutService: AboutService
  ) {}

  dataNotify: Subject<INotify> = new Subject();

  version: string = environvent.version;
  dateVersion: string = localStorage['dateVersion'] || 'Unknown';
  dateCheck: string = localStorage['dateCheck'] || 'Unknown';

  lastVersion: string = '';
  pathUpdate: string = '';
  
  windUpdates: boolean = false;
  downloadProgress: boolean = false;

  ngOnInit(): void {
    this.getDate();
    this.checkUpdate();
  }

  matchVersion(lastVer: string) {
    const v1Components = lastVer.split('.').map(Number);
    const v2Components = this.version.split('.').map(Number);

    for (let i = 0; i < Math.max(v1Components.length, v2Components.length); i++) {
      const v1Value = v1Components[i] || 0;
      const v2Value = v2Components[i] || 0;

      if (v1Value < v2Value) {
        return false;
      } else if (v1Value > v2Value) {
        return true;
      }
    }

    return false;
  }

  formatDate(date: string) {
    return new Date(date).toISOString().split("T")[0];
  }

  getDate() {
    this.aboutService.getDate(this.version).subscribe({
      next: (res: any) => {
        if (res && res.published_at) {
          localStorage['dateVersion'] = String(this.formatDate(res.published_at));
          this.dateVersion = String(this.formatDate(res.published_at));
        } else {
          throw Error("Invalid request");
        }
      },
      error: (err: any) => {
        console.error(err);
        this.downloadProgress = false;
        this.dataNotify.next({status: 'error', text: err.status + ' — ' + err.message});
      }
    });
  }
  
  checkUpdate() {
    localStorage['dateCheck'] = String(this.formatDate(new Date().toUTCString()));
    this.aboutService.checkUpdate().subscribe({
      next: (res: any) => {
        if (res && res.tag_name) {
          const lastVer: string = res.tag_name;
          setTimeout(() => {
            if (this.matchVersion(lastVer)) {
              this.dataNotify.next({status: 'warning', text: "A new version is available!"});
              this.windUpdates = true;
              this.lastVersion = lastVer;
            } else {
              this.dataNotify.next({status: 'success', text: "You have the latest version!"});
            }
          }, 1000);
        } else {
          throw Error("Invalid request");
        }
      },
      error: (err: any) => {
        console.error(err);
        this.dataNotify.next({status: 'error', text: err.status + ' — ' + err.message});
      }
    });
  }

  downloadFile() {
    this.downloadProgress = true,
    this.dataNotify.next({status: 'warning', text: "Wait until the program update is downloaded!"});
    this.aboutService.downloadUpdate(this.lastVersion)
    .then((data: any) => {
      if (data) {
        this.dataNotify.next({status:'success', text: "The new version of the program has been successfully downloaded!"});
        this.pathUpdate = data;
      } else {
        throw Error(data);
      }
    })
    .catch((err: any) => {
      console.error(err);
      this.dataNotify.next({status: 'error', text: err});
    });
    this.downloadProgress = false;
    this.windUpdates = false;
  }

  openFile() {
    this.aboutService.openFile(this.pathUpdate)
    .catch((err: any) => {
      console.error(err);
      this.dataNotify.next({status: 'error', text: err});
    })
  }
}

<div class="flex flex-col items-center w-full">
  <img src="/assets/images/icon.png" alt="icon app" class="!w-1/5" />
  <span class="text-3xl font-bold">All In One Toolkit</span>
  <div class="mt-3 text-xl font-bold">
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Version</span>
      <span>{{version}}</span>
    </div>
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Date of released</span>
      <span>{{dateVersion}}</span>
    </div>
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Author</span>
      <span>Dmitriy303</span>
    </div>
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Company</span>
      <span>TechCraft Solutions</span>
    </div>
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Year of creation</span>
      <span>2023</span>
    </div>
    <div class="flex flex-row gap-x-3 justify-center">
      <span class="!text-gray-600 dark:!text-gray-300">Last checked</span>
      <span>{{dateCheck}}</span>
    </div>
  </div>
  <div class="text-xl font-bold mt-3">
    <span class="styleLink" (click)="checkUpdate()"> Check for updates...</span>
  </div>
  @if (pathUpdate != '') {
    <div class="text-xl font-bold mt-3">
      <span class="styleLink" (click)="openFile()">Open new version</span>
    </div>
  }
</div>

@if (windUpdates) {
  <div class="styleBackWind">
    <div class="styleWind">
      <div class="border-b-2 pb-2 styleBorderSolid">
        <span class="text-xl font-bold">Updating the program</span>
      </div>
      <div class="flex flex-col my-3 gap-y-2">
        <span>Do you want to download the update?</span>
        @if (downloadProgress) {
          <div class="w-full bg-gray-300 rounded-full mb-4 dark:bg-gray-700 h-[20px]">
            <div class="w-full rounded-full h-[20px]" [style]="{backgroundImage: 'repeating-linear-gradient( 45deg, transparent, transparent 10px, rgb(5 122 85) 10px, rgb(5 122 85) 20px )', animation: 'slide 4s linear infinite'}"></div>
          </div>
        }
      </div>
      <div class="flex flex-row justify-end gap-x-3 pt-2 border-t-2 styleBorderSolid">
        <button class="styleBut" (click)="windUpdates = false">No</button>
        <button class="styleBut" (click)="downloadFile()">Yes</button>
      </div>
    </div>
  </div>
}

<app-window-notify
  [dataNotify]="dataNotify">
</app-window-notify>

// src/pages/About.tsx
import React from "react";
import { invoke } from "@tauri-apps/api/tauri";
import { Link } from "react-router-dom";
import { ChevronBackCircleOutline } from "react-ionicons";

import { ENV } from "../env";
import WindNotify from "./WindNotify";

class About extends React.Component<{numWind: number, onChangeData: any}> {
  constructor(props: any) {
    super(props);
  }

  childRef: any = React.createRef();

  state = {
    dateVersion: localStorage['dateVersion'] || 'Unknown',
    dateCheck: localStorage['dateCheck'] || 'Unknown',
    lastVersion: '',
    pathUpdate: '',
    windUpdates: false,
    downloadProgress: false,
  }

  componentDidMount(): void {
    this.getDate();
    this.checkUpdates();
  }

  changeNumWind(numWind: number) {
    this.props.onChangeData(Number(numWind));
  }

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  }

  matchVersion(lastVer: string) {
    let tempVer = lastVer.slice(1).split(".");
    let curVer = ENV.version.split(".");
    return (Number(tempVer[0]) > Number(curVer[0]) || Number(tempVer[1]) > Number(curVer[1]) || Number(tempVer[2]) > Number(curVer[2]));
  }

  formatDate(date: string) {
    return new Date(date).toISOString().split("T")[0];
  }

  async getDate() {
    await fetch(`https://api.github.com/repos/rusnakdima/All_In_One_Toolkit_Tauri/releases/tags/v${ENV.version}`)
    .then(response => response.json())
    .then(json => {
      if (json && json.published_at) {
        localStorage['dateVersion'] = String(this.formatDate(json.published_at));
        this.setState({
          dateVersion: String(this.formatDate(json.published_at)),
        });
      } else {
        throw Error("Invalid request");
      }
    })
    .catch(err => {
      console.error(err);
      this.alertNotify("bg-red-700", "Error sending the request!");
    });
  }

  public async checkUpdates() {
    localStorage['dateCheck'] = String(this.formatDate(new Date().toUTCString()));
    this.setState({
      dateCheck: String(this.formatDate(new Date().toUTCString()))
    });
    await fetch('https://api.github.com/repos/rusnakdima/All_In_One_Toolkit_Tauri/releases/latest')
    .then(response => response.json())
    .then(json => {
      if (json && json.tag_name) {
        const lastVer: string = json.tag_name;
        setTimeout(() => {
          if (this.matchVersion(lastVer)) {
            this.alertNotify("bg-yellow-500", "A new version is available!");
            this.setState({
              windUpdates: true,
              lastVersion: lastVer
            });
          } else {
            this.alertNotify("bg-green-700", "You have the latest version!");
          }
        }, 1000);
      } else {
        throw Error("Invalid request");
      }
    })
    .catch(err => {
      console.error(err);
      this.alertNotify("bg-red-700", "Error sending the request!");
    });
  }

  async downloadFile() {
    this.setState({
      downloadProgress: true
    })
    this.alertNotify("bg-yellow-500", "Wait until the program update is downloaded!");
    await invoke("download_update", {"url": `https://github.com/rusnakdima/All_In_One_Toolkit_Tauri/releases/download/${this.state.lastVersion}/all_in_one_toolkit.exe`, "fileName": "all_in_one_toolkit.exe"})
    .then((data: any) => {
      if (data) {
        this.alertNotify("bg-green-700", "The new version of the program has been successfully downloaded!");
        this.setState({
          pathUpdate: data,
        });
      } else {
        throw Error(data);
      }
    })
    .catch((err: any) => {
      console.error(err)
      this.alertNotify("bg-red-700", `${err}`);
    });
    this.setState({
      windUpdates: false,
      downloadProgress: false
    });
  }

  async openFile() {
    await invoke("open_file", {'path': this.state.pathUpdate})
    .catch((err: any) => {
      console.error(err)
      this.alertNotify("bg-red-700", `${err}`);
    });
  }

  render() {
    return (
      <>
        <div className={`flex flex-col gap-y-5 ${(this.props.numWind > 2) ? 'w-full lg:w-1/3' : (this.props.numWind > 1) ? 'w-full lg:w-1/2' : 'w-full'}`}>
          <div className="flex flex-row justify-between items-center border-b-2 styleBorderSolid pb-2">
            <div className="flex flex-row gap-x-2 text-2xl font-bold">
              <Link to="/"><ChevronBackCircleOutline cssClasses="styleIonIcon" /></Link>
              <span>About program</span>
            </div>
            <select className="styleSelect !w-min" onChange={(event: any) => {this.changeNumWind(event.target.value)}} value={this.props.numWind}>
              <option value={1}>1 window</option>
              <option value={2}>2 windows</option>
              <option value={3}>3 windows</option>
            </select>
          </div>

          <div className="flex flex-col items-center">
            <img alt="Icon program" src="/assets/images/icon.png" className="!w-1/5" />
            <span className="text-3xl font-bold">All In One Toolkit</span>
            <div className="mt-3 text-xl font-bold">
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Version</span>
                <span>{ENV.version}</span>
              </div>
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Date</span>
                <span>{this.state.dateVersion}</span>
              </div>
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Author</span>
                <span>Dmitriy303</span>
              </div>
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Company</span>
                <span>TechCraft Solutions</span>
              </div>
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Year of creation</span>
                <span>2023</span>
              </div>
              <div className="flex flex-row gap-x-3 justify-center">
                <span className="text-gray-600 dark:text-gray-300">Date of last check</span>
                <span>{this.state.dateCheck}</span>
              </div>
            </div>
            <div className="text-xl font-bold mt-3">
              <button className="styleLink" onClick={() => {this.checkUpdates()}}> Check for updates...</button>
            </div>
            {this.state.pathUpdate != '' &&
              <div className="text-xl font-bold mt-3">
                <button className="styleLink" onClick={() => {this.openFile()}}>Open new version</button>
              </div>
            }
          </div>
        </div>

        {this.state.windUpdates && <div className="styleBackWind">
          <div className="styleWind">
            <div className="border-b-2 pb-2 styleBorderSolid">
              <span className="text-xl font-bold">Updating the program</span>
            </div>
            <div className="flex flex-col my-3 gap-y-2">
              <span>Do you want to download the update?</span>
              {this.state.downloadProgress &&
                <div className="w-full bg-gray-300 rounded-full mb-4 dark:bg-gray-700" style={{height: "20px"}}>
                  <div className="w-full rounded-full" style={{height: "20px", backgroundImage: 'repeating-linear-gradient( 45deg, transparent, transparent 10px, rgb(5 122 85) 10px, rgb(5 122 85) 20px )', animation: 'slide 4s linear infinite'}}></div>
                </div>
              }
            </div>
            <div className="flex flex-row justify-end gap-x-3 pt-2 border-t-2 styleBorderSolid">
              <button className="styleBut" onClick={() => {this.setState({windUpdates: false})}}>No</button>
              <button className="styleBut" onClick={() => {this.downloadFile()}}>Yes</button>
            </div>
          </div>
        </div>}

        <WindNotify ref={this.childRef} />
      </>
    );
  };
};

export default About;
