// src/app/views/shared/nav/nav.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-nav',
  standalone: true,
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ],
  imports: [CommonModule, RouterModule],
  templateUrl: './nav.component.html'
})
export class NavComponent implements OnInit {
  title: string = '';

  constructor() {}

  @Input() isShowNav: Subject<boolean> = new Subject();

  showNav: boolean = false;

  ngOnInit(): void {
    this.isShowNav.subscribe((value: boolean) => {
      this.showNav = value;
    });
  }

}

<div class="fixed top-0 left-0 m-0 p-0 z-40 w-full h-screen bg-white/60 dark:bg-black/30" [ngClass]="showNav ? 'block' : '-translate-x-full'" (click)="showNav = false">
  <div class="w-64 p-4 bg-gray-200 dark:bg-zinc-800 h-screen transition-transform" [ngClass]="showNav ? '' : '-translate-x-full'">
    <span class="text-base font-semibold text-gray-500 dark:text-gray-400 uppercase">Menu</span>
    <div class="flex flex-col py-4 overflow-y-auto h-full space-y-2 font-medium">
      <div class="styleLinkMenu" [routerLink]="['/home']">
        <img src="https://cdn-icons-png.flaticon.com/512/1828/1828673.png" alt="dashboard" class="w-7 h-7">
        <span>Dashboard</span>
      </div>
      <div class="styleLinkMenu" [routerLink]="['/about']">
        <img src="https://cdn-icons-png.flaticon.com/512/9195/9195785.png" alt="about" class="w-7 h-7">
        <span>About</span>
      </div>
    </div>
  </div>
</div>

// src/pages/Nav.tsx
import React from 'react';
import { Link } from "react-router-dom";
import { HomeOutline, InformationOutline } from "react-ionicons";

interface HomeState {
  recentAction: Array<{ to: string; icon: string; name: string }>;
}

class Nav extends React.Component<{}, HomeState> {
  state: HomeState = {
    recentAction: [],
  };

  componentDidMount(): void {
    let recAct = localStorage["recAct"];
    if(recAct && recAct != ''){
      this.setState({
        recentAction: JSON.parse(recAct)
      });
    }
  }

  addLink(to: string, icon: string, name: string): void{
    let tempObj = { "to": to, "icon": icon, "name": name };
    if(!this.state.recentAction.find((item: any) => item['to'] == tempObj['to'])){
      this.state.recentAction.unshift(tempObj)
    } else {
      this.state.recentAction.splice((this.state.recentAction.findIndex((item: any) => item == tempObj)), 1);
      this.state.recentAction.unshift(tempObj);
    }
    if(this.state.recentAction.length > 4) this.state.recentAction.pop();
    localStorage["recAct"] = JSON.stringify(this.state.recentAction);
  }

  render(){
    return (
      <div className="fixed top-0 left-0 m-0 p-0 z-40 w-full h-screen -translate-x-full bg-white/60 dark:bg-black/30" id="menuBack">
        <div className="w-64 p-4 bg-gray-200 dark:bg-zinc-800 h-screen transition-transform -translate-x-full">
          <span className="text-base font-semibold text-gray-500 uppercase dark:text-gray-400">Menu</span>
          <div className="flex flex-col py-4 overflow-y-auto h-full space-y-2 font-medium">
            <Link to="/" className="styleLinkMenu"><HomeOutline cssClasses="styleIonIcon" /> <span>Home</span></Link>
            <Link to="/about" className="styleLinkMenu"><InformationOutline cssClasses="styleIonIcon" /> <span>About</span></Link>
          </div>
        </div>
      </div>
    );
  };
};

export default Nav;
