// src/app/views/xls-to-json/xls-to-json.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { invoke } from '@tauri-apps/api/tauri';
import { Subject } from 'rxjs';

/* components */
import { FileInputComponent } from '@views/shared/fields/file-input/file-input.component';
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';
import { HeaderPageComponent } from '@views/shared/header-page/header-page.component';

@Component({
  selector: 'app-xls-to-json',
  standalone: true,
  imports: [CommonModule, HeaderPageComponent, FileInputComponent, WindowNotifyComponent],
  templateUrl: './xls-to-json.component.html'
})
export class XlsToJsonComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();
  
  typeFile: string = 'xls';
  fileName: string = '';
  dataXls: Array<any> = [];
  dataJson: {[key: string]: any} | null = null;
  pathNewFile: string = '';

  setDataFile(dataFile: any) {
    this.dataXls = JSON.parse(dataFile);
  }

  setFileName(event: any) {
    this.fileName = event;
  }

  setData(event: any) {
    if (event.target.value != '') {
      this.dataXls = event.target.value.split("\n").map((elem: string) => elem.split("\t"));
    } else {
      this.dataNotify.next({ status: "error", text: "The field is empty! Insert the data!"});
    }
  }

  parseData(dataArr: Array<any>) {
    this.dataJson = {"root": {"array": []}};
    let strokeF = dataArr[0];
    dataArr.splice(0, 1);
    dataArr.forEach((row: any) => {
      let tempObj: {[key: string]: any} = {};
      row.forEach((cell: any, index: number) => {
        const key: string = (strokeF[index]) ? strokeF[index].replace(/[\" \"]/gi,"") : `column${index}`;
        tempObj[key] = cell;
      });
      this.dataJson!["root"]["array"].push(tempObj);
    });
  }

  convertData() {
    if (this.dataXls.length > 0) {
      this.parseData(this.dataXls);
  
      if (this.dataJson && Object.keys(this.dataJson).length > 0) {
        this.dataNotify.next({ status: 'success', text: "The data has been successfully converted!" });
      } else {
        this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
      }
    } else {
      this.dataNotify.next({ status: 'error', text: "There is no data for conversion!" });
    }
  }

  async saveData() {
    if (this.dataJson) {
      const nameNewFile = (this.fileName != '') ? /^(.+)\..+$/.exec(this.fileName)![1] : 'xls_to_json';
      await invoke("write_data_to_file", {"name": nameNewFile, "data": JSON.stringify(this.dataJson), "ext": "json"})
      .then((data: any) => {
        this.pathNewFile = data;
        this.dataNotify.next({ status: 'success', text: `The data has been successfully saved to a file "${data}"!` });
      })
      .catch((err: any) => console.error(err));
    } else if (this.dataJson == null) {
      this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
    }
  }

  async openFile() {
    if (this.pathNewFile != '') {
      await invoke("open_file_in_app", {"path": this.pathNewFile})
      .then(() => {
        this.dataNotify.next({ status: 'warning', text: "Wait a bit until the program starts to read this file format!" });
      })
      .catch((err: any) => console.error(err));
    } else {
      this.dataNotify.next({ status: 'error', text: "You didn't save the file to open it!" });
    }
  }
}

<app-header-page></app-header-page>

<div class="flex flex-col gap-y-5 m-5">
  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Select a tabular document with data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <app-file-input [typeFile]="typeFile" (dataFile)="setDataFile($event)" (reciveFileName)="setFileName($event)"></app-file-input>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Insert data from a table (copy a table from any source)</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <textarea class="styleTextarea" (change)="setData($event)" rows="7"></textarea>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  @if (dataJson) {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="saveData()">Save a data</button>
    </div>
  }

  @if (pathNewFile != '') {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="openFile()">Open the last saved file</button>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>

// src/pages/XlsToJson.tsx
import React from "react";

import * as XLSX from "xlsx";

import WindNotify from "./WindNotify";

import { invoke } from "@tauri-apps/api/tauri";

class XlsToJson extends React.Component {
  childRef: any = React.createRef();

  file: any = null;
  dataField: string = "";
  dataJson: {[key: string]: any} = {};

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  };

  convertDataFun = (data: any[]) => {
    this.dataJson = {"root": []};
    let strokeF = data[0];
    data.splice(0, 1);
    data.forEach((element) => {
      let tempObj: {[key: string]: any} = {};
      element.forEach((elem: any, index: number) => tempObj[strokeF[index]] = elem);
      this.dataJson["root"].push(tempObj);
    });

    if (Object.keys(this.dataJson).length > 0) {
      this.alertNotify("bg-green-700", "The data has been successfully converted!");
    } else {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  };

  parseDataFileFun = async () => {
    if(this.file != null){
      const reader = new FileReader();
      reader.onload = (e: any) => {
        const text = (e.target.result);
        const workbook = XLSX.read(text, {type:'binary'});
        const worksheet = workbook.Sheets[workbook.SheetNames[0]];
        const data = XLSX.utils.sheet_to_json(worksheet, { header: 1 });
        this.convertDataFun(data);
      }
      reader.readAsBinaryString(this.file)
    } else {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    }
  };

  parseDataFieldFun = () => {
    if(this.dataField != ''){
      const data = this.dataField.split("\n").map((elem) => elem.split("\t"));
      this.convertDataFun(data);
    } else {
      this.alertNotify("bg-red-700", "The field is empty! Insert the data!");
    }
  };

  saveDataFileFun = async () => {
    if(this.file != null || Object.keys(this.dataJson).length > 0){
      await invoke("xls_to_json", {"name": (this.file) ? /^(.+)\..+$/.exec(this.file["name"])![1] : 'xls_to_json', "data": JSON.stringify(this.dataJson)})
      .then((data: any) => {
        this.alertNotify("bg-green-700", `The data has been successfully saved to a file "${data}"!`);
      })
      .catch((err: any) => console.error(err));
    } else if(this.file == null){
      this.alertNotify("bg-red-700", "You have not selected a file!");
    } else if (Object.keys(this.dataJson).length == 0){
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  };

  render(){
    return (
      <>
        <div className="flex flex-col">
          <span className="text-2xl font-bold border-b-2 styleBorderSolid">Converter XLS to JSON</span>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Select a tabular document with data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <input className="styleFileInput" type="file" onChange={(event: any) => {this.file = event.target.files[0]}} accept=".xls, .xlsx, .xlsm" />
              <button className="styleBut w-max" onClick={() => {this.parseDataFileFun()}}>Convert a data</button>
            </div>
          </details>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Insert data from a table (copy a table from any source)</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <textarea className="styleTextarea" name="field" onChange={(event: any) => {this.dataField = event.target.value}} rows={7}></textarea>
              <button className="styleBut w-max" onClick={() => {this.parseDataFieldFun()}}>Convert a data</button>
            </div>
          </details>
          
          <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.saveDataFileFun()}}>Save a data</button>
          </div>
        </div>

        <WindNotify ref={this.childRef} />
      </>
    );
  };
};

export default XlsToJson;
