// src/app/views/xml-to-xls/xml-to-xls.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { invoke } from '@tauri-apps/api/tauri';
import { Subject } from 'rxjs';

/* components */
import { FileInputComponent } from '@views/shared/fields/file-input/file-input.component';
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';
import { HeaderPageComponent } from '@views/shared/header-page/header-page.component';
import { XmlToJsonComponent } from '@views/xml-to-json/xml-to-json.component';
import { JsonToXlsComponent } from '@views/json-to-xls/json-to-xls.component';

@Component({
  selector: 'app-xml-to-xls',
  standalone: true,
  imports: [CommonModule, HeaderPageComponent, FileInputComponent, WindowNotifyComponent],
  templateUrl: './xml-to-xls.component.html'
})
export class XmlToXlsComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();
  
  typeFile: string = 'xml';
  fileName: string = '';
  dataXml: string = '';
  dataXls: Array<any> = [];
  pathNewFile: string = '';

  ngOnInit(): void {}

  setDataFile(dataFile: any) {
    this.dataXml = dataFile;
  }

  setFileName(event: any) {
    this.fileName = event;
  }

  setData(event: any) {
    try {
      this.dataXml = event.target.value;
    } catch (err: any) {
      console.error(err);
      this.dataNotify.next({ status: 'error', text: err.toString() });
    }
  }

  convertData() {
    if (this.dataXml != '') {
      let parser = new DOMParser();
      let xmlDoc = parser.parseFromString(this.dataXml, 'text/xml');
      const dataJson = XmlToJsonComponent.prototype.parseData(Array.from(xmlDoc.children[0].children));
      this.dataXls = JsonToXlsComponent.prototype.parseObj(dataJson);
  
      if (this.dataXls.length > 0) {
        this.dataNotify.next({ status: 'success', text: "The data has been successfully converted!" });
      } else {
        this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
      }
    } else {
      this.dataNotify.next({ status: 'error', text: "There is no data for conversion!" });
    }
  }

  async saveData() {
    if (this.dataXls.length > 0) {
      const nameNewFile = (this.fileName != '') ? /^(.+)\..+$/.exec(this.fileName)![1] : 'xml_to_xls';
      await invoke("write_xls_data_to_file", {"name": nameNewFile, "data": this.dataXls})
      .then((data: any) => {
        this.pathNewFile = data;
        this.dataNotify.next({ status: 'success', text: `The data has been successfully saved to a file "${data}"!` });
      })
      .catch((err: any) => console.error(err));
    } else if (this.dataXls.length == 0) {
      this.dataNotify.next({ status: 'error', text: "No data was received from the file!" });
    }
  }

  async openFile() {
    if (this.pathNewFile != '') {
      await invoke("open_file_in_app", {"path": this.pathNewFile})
      .then(() => {
        this.dataNotify.next({ status: 'warning', text: "Wait a bit until the program starts to read this file format!" });
      })
      .catch((err: any) => console.error(err));
    } else {
      this.dataNotify.next({ status: 'error', text: "You didn't save the file to open it!" });
    }
  }
}

<app-header-page></app-header-page>

<div class="flex flex-col gap-y-5 m-5">
  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Select the XML file with the data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <app-file-input [typeFile]="typeFile" (dataFile)="setDataFile($event)" (reciveFileName)="setFileName($event)"></app-file-input>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  <details class="styleDetails">
    <summary>
      <span class="text-xl font-bold">Insert XML data</span>
    </summary>

    <div class="flex flex-col gap-y-3 mt-2">
      <textarea class="styleTextarea" (change)="setData($event)" rows="7"></textarea>
      <button class="styleBut w-max" (click)="convertData()">Convert a data</button>
    </div>
  </details>

  @if (dataXls.length > 0) {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="saveData()">Save a data</button>
    </div>
  }

  @if (pathNewFile != '') {
    <div class="flex flex-row gap-x-3">
      <button class="styleBut" (click)="openFile()">Open the last saved file</button>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>

// src/pages/XmlToXls.tsx
import React from "react";
import { invoke } from "@tauri-apps/api/tauri";
import { Link } from "react-router-dom";
import { ChevronBackCircleOutline } from "react-ionicons";

import WindNotify from "./WindNotify";

class XmlToXls extends React.Component<{numWind: number, onChangeData: any}> {
  constructor(props: any) {
    super(props);
  }

  childRef: any = React.createRef();

  file: any = null;
  dataField: string = "";
  dataXls: Array<any> = [];
  
  state = {
    pathNewFile: ""
  }

  changeNumWind(numWind: number) {
    this.props.onChangeData(Number(numWind));
  }

  alertNotify(color: string, title: string) {
    this.childRef.current.alertNotify(color, title);
  }

  parseData(xmlNodes: Array<any>, startPos: number = 0) {
    let table: Array<Array<string>> = [];
    let tempHead: Array<string> = [];
    tempHead.push(...[...Array(startPos).fill(''), 'Key', 'Value']);
    table.push(tempHead);
    xmlNodes.forEach((elem: any) => {
      let tempRow: Array<string> = [];
      tempRow.push(...[...Array(startPos).fill(''), elem.nodeName]);
      if ([...elem.children].length > 0) {
        this.parseData([...elem.children], startPos + 1).forEach((row: Array<string>, iRow: number) => {
          if (iRow == 0) {
            tempRow.push(...row.slice(startPos + 1));
            table.push(tempRow);
          } else {
            table.push(row);
          }
        });
      } else {
        tempRow.push(elem.textContent.toString());
        table.push(tempRow);
      }
    });
    return table;
  }

  convertDataFun(dataXml: string) {
    let parser = new DOMParser();
    let xmlDoc = parser.parseFromString(dataXml, 'text/xml');
    this.dataXls = this.parseData([...xmlDoc.children]);

    if (Array.isArray(this.dataXls)) {
      this.alertNotify("bg-green-700", "The data has been successfully converted!");
    } else {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  }

  async parseDataFileFun() {
    if (this.file != null) {
      const fileUrl = URL.createObjectURL(this.file);
      const response = await fetch(fileUrl);
      const text = await response.text();
      if (text != null && text != '') {
        const dataXml = text;
        this.convertDataFun(dataXml);
      } else {
        this.alertNotify("bg-red-700", "The file is empty!");
      }
    } else {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    }
  }

  parseDataFieldFun() {
    if (this.dataField != '') {
      const dataXml = this.dataField;
      this.convertDataFun(dataXml);
    } else {
      this.alertNotify("bg-red-700", "The field is empty! Insert the data!");
    }
  }

  async saveDataFileFun() {
    if (this.file != null || this.dataXls.length > 0) {
      const nameNewFile = (this.file) ? /^(.+)\..+$/.exec(this.file["name"])![1] : 'xml_to_xls';
      await invoke("xml_to_xls", {"name": nameNewFile, "data": JSON.stringify(this.dataXls)})
      .then((data: any) => {
        this.setState({
          pathNewFile: data
        });
        this.alertNotify("bg-green-700", `The data has been successfully saved to a file "${data}"!`);
      })
      .catch((err: any) => console.error(err));
    } else if (this.file == null) {
      this.alertNotify("bg-red-700", "You have not selected a file!");
    } else if (this.dataXls.length == 0) {
      this.alertNotify("bg-red-700", "No data was received from the file!");
    }
  }

  async openFileFun() {
    if (this.state.pathNewFile != '') {
      await invoke("open_file", {"path": this.state.pathNewFile})
      .then(() => {
        this.alertNotify("bg-green-700", "Wait a bit until the program starts to read this file format!");
      })
      .catch((err: any) => console.error(err));
    } else {
      this.alertNotify("bg-red-700", "You didn't save the file to open it!");
    }
  }

  render() {
    return (
      <>
        <div className={`flex flex-col gap-y-5 ${(this.props.numWind > 2) ? 'w-full lg:w-1/3' : (this.props.numWind > 1) ? 'w-full lg:w-1/2' : 'w-full'}`}>
          <div className="flex flex-row justify-between items-center border-b-2 styleBorderSolid pb-2">
            <div className="flex flex-row gap-x-2 text-2xl font-bold">
              <Link to="/"><ChevronBackCircleOutline cssClasses="styleIonIcon" /></Link>
              <span>Converter XML to XLS</span>
            </div>
            <select className="styleSelect !w-min" onChange={(event: any) => {this.changeNumWind(event.target.value)}} value={this.props.numWind}>
              <option value={1}>1 window</option>
              <option value={2}>2 windows</option>
              <option value={3}>3 windows</option>
            </select>
          </div>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Select the XML file with the data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <input className="styleFileInput" type="file" onChange={(event: any) => {this.file = event.target.files[0]}} accept=".xml" />
              <button className="styleBut w-max" onClick={() => {this.parseDataFileFun()}}>Convert a data</button>
            </div>
          </details>

          <details className="styleDetails">
            <summary>
              <span className="text-xl font-bold">Insert XML data</span>
            </summary>

            <div className="flex flex-col gap-y-3">
              <textarea className="styleTextarea" name="field" onChange={(event: any) => {this.dataField = event.target.value}} rows={7}></textarea>
              <button className="styleBut w-max" onClick={() => {this.parseDataFieldFun()}}>Convert a data</button>
            </div>
          </details>
          
          <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.saveDataFileFun()}}>Save a data</button>
          </div>

          {this.state.pathNewFile != '' && <div className="flex flex-row gap-x-3">
            <button className="styleBut" onClick={() => {this.openFileFun()}}>Open the last saved file</button>
          </div>}
        </div>

        <WindNotify ref={this.childRef} />
      </>
    );
  };
};

export default XmlToXls;
