// src/pages/UrlEncDec.tsx
import React from "react";

class UrlEncDec extends React.Component {
  urlInput: string = "";
  state = {
    outputText: ""
  };

  encodeFun = () => {
    const outputEl = document.querySelector("#output") as HTMLTextAreaElement | null;
    if(outputEl != null){
      outputEl.setAttribute("style", "display: block");
      const encodeUrl = encodeURIComponent(this.urlInput);
      this.setState({
        outputText: encodeUrl
      });
    }
  };

  decodeFun = () => {
    const outputEl = document.querySelector("#output") as HTMLTextAreaElement | null;
    if(outputEl != null){
      outputEl.setAttribute("style", "display: block");
      const decodeUrl = decodeURIComponent(this.urlInput);
      this.setState({
        outputText: decodeUrl
      });
    }
  };

  render() {
    return (
      <div className="flex flex-col gap-y-3">
        <span className="text-2xl font-bold border-b-2 styleBorderSolid">Encode/Decode URL</span>
        
        <label className="styleLabel">Enter the link:</label>
        <textarea className="styleField" onChange={(event: any) => { this.urlInput = event.target.value }}></textarea>

        <div className="flex flex-row gap-x-2">
          <button className="styleBut" onClick={() => {this.encodeFun()}}>Encode</button>
          <button className="styleBut" onClick={() => {this.decodeFun()}}>Decode</button>
        </div>
        
        <textarea id="output" className="styleField" style={{"display": "none"}} defaultValue={this.state.outputText}></textarea>
      </div>
    );
  };
};

export default UrlEncDec;

// src/app/views/url-enc-dec/url-enc-dec.component.ts
/* system libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Subject } from 'rxjs';

/* components */
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

@Component({
  selector: 'app-url-enc-dec',
  standalone: true,
  imports: [CommonModule, WindowNotifyComponent],
  templateUrl: './url-enc-dec.component.html'
})
export class UrlEncDecComponent {
  title: string = '';

  constructor() { }

  dataNotify: Subject<INotify> = new Subject();
  
  urlInput: string = '';
  outputText: string = '';

  ngOnInit(): void {}

  setData(event: any) {
    this.urlInput = event.target.value;
  }

  encode() {
    try {
      const encodeUrl = encodeURIComponent(this.urlInput);
      this.outputText = encodeUrl;
    } catch (error: any) {
      console.error(error);
      this.dataNotify.next({ status: 'error', text: error.toString() });
    }
  }
  
  decode() {
    try {
      const decodeUrl = decodeURIComponent(this.urlInput);
      this.outputText = decodeUrl;
    } catch (error: any) {
      console.error(error);
      this.dataNotify.next({ status: 'error', text: error.toString() });
    }
  }
}

<div class="flex flex-col gap-y-5 w-full">
  <label class="styleLabel">Enter the link</label>
  <textarea class="styleField" (change)="setData($event)"></textarea>

  <div class="flex flex-row gap-x-2">
    <button class="styleBut" (click)="encode()">Encode</button>
    <button class="styleBut" (click)="decode()">Decode</button>
  </div>

  @if (outputText != '') {
    <div class="flex flex-col gap-y-2 styleBorderSolidLite border p-3">
      <span class="font-semibold text-xl">Results</span>
      <textarea class="styleTextarea" [value]="outputText"></textarea>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>
