// src/pages/Base64EncDec.tsx
import React from "react";

class Base64EncDec extends React.Component {
  baseInput: string = "";
  state = {
    outputText: ""
  }

  encodeFun = () => {
    const outputEl = document.querySelector("#output") as HTMLTextAreaElement | null;
    if(outputEl != null){
      outputEl.setAttribute("style", "display: block");
      try {
        const encodeData = btoa(this.baseInput);
        this.setState({
          outputText: encodeData
        });
      } catch (error) {
        console.error(error);
      }
    }
  };

  decodeFun = () => {
    const outputEl = document.querySelector("#output") as HTMLTextAreaElement | null;
    if(outputEl != null){
      outputEl.setAttribute("style", "display: block");
      try {
        const decodeData = atob(this.baseInput);
        this.setState({
          outputText: decodeData
        });
      } catch (error) {
        console.error(error);
      }
    }
  };

  render(){
    return(
      <div className="flex flex-col gap-y-3">
        <span className="text-2xl font-bold border-b-2 styleBorderSolid">Encode data to base64 / Decode data from base64</span>
        
        <label className="styleLabel">Enter the data:</label>
        <textarea className="styleField" onChange={(event: any) => { this.baseInput = event.target.value }}></textarea>

        <div className="flex flex-row gap-x-2">
          <button className="styleBut" onClick={() => {this.encodeFun()}}>Encode</button>
          <button className="styleBut" onClick={() => {this.decodeFun()}}>Decode</button>
        </div>

        <textarea id="output" className="styleField" style={{"display": "none"}} defaultValue={this.state.outputText}></textarea>
      </div>
    );
  };
};

export default Base64EncDec;

// src/app/views/base64-enc-dec/base64-enc-dec.component.ts
/* syste, libraries */
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Subject } from 'rxjs';

/* components */
import { INotify, WindowNotifyComponent } from '@views/shared/window-notify/window-notify.component';

@Component({
  selector: 'app-base64-enc-dec',
  standalone: true,
  imports: [CommonModule, WindowNotifyComponent],
  templateUrl: './base64-enc-dec.component.html'
})
export class Base64EncDecComponent {
  title: string = '';

  constructor() {}

  dataNotify: Subject<INotify> = new Subject();

  baseInput: string = '';
  outputText: string = '';

  ngOnInit(): void {}

  setData(event: any) {
    this.baseInput = event.target.value;
  }

  encode() {
    try {
      const encodeData = btoa(this.baseInput);
      this.outputText = encodeData;
    } catch (error: any) {
      console.error(error);
      this.dataNotify.next({ status: 'error', text: error.toString() });
    }
  }
  
  decode() {
    try {
      const decodeData = atob(this.baseInput);
      this.outputText = decodeData;
    } catch (error: any) {
      console.error(error);
      this.dataNotify.next({ status: 'error', text: error.toString() });
    }
  }
}

<div class="flex flex-col gap-y-5 w-full">
  <label class="styleLabel">Enter the data</label>
  <textarea class="styleField" (change)="setData($event)"></textarea>

  <div class="flex flex-row gap-x-2">
    <button class="styleBut" (click)="encode()">Encode</button>
    <button class="styleBut" (click)="decode()">Decode</button>
  </div>

  @if (outputText != '') {
    <div class="flex flex-col gap-y-2 styleBorderSolidLite border p-3">
      <span class="font-semibold text-xl">Results</span>
      <textarea class="styleTextarea" [value]="outputText"></textarea>
    </div>
  }
</div>

<app-window-notify
  [dataNotify]="dataNotify"
></app-window-notify>
